apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- service-account.yaml
- vllm-deployment.yaml
- vllm-gemma-deployment.yaml
- rag-deployment.yaml
- rag-service.yaml

commonLabels:
  project: inf4rag
  component: core
